### ISSUE TITLE
Complete metadata recorded by DS runs

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotscience-committer#4]
We only provide a subset of the full run metadata spec right now.

This information goes into the project dot commit and is available for viewing in the Web interface as a historical audit trail, and is also returned as the "task output" back to the user interface that's waiting for that specific run (eg, `ds run`).

The metadata spec is here:

https://github.com/dotmesh-io/ds/blob/master/docs/run-metadata-format.md

The code that generates the medata is in hack.py (see the lifecycle of the `projectMetadata` variable), but most of the needed information is missing and needs to be passed in from the gateway (runner name), runner (runner version), agent (agent version, whether the run succeeded or failed, start time, end time, CPU used, RAM used), etc.

**Comment by rusenask** [comment]
Task has a field "labels",

```
message Task {
  string id = 1;
  string name = 2;                // task name. Based on task names different task executors will trigger 
  string payload = 3;             // json/gob/whatever encoded payload of the task
  string desiredStatus = 4;       // desired status of the task
  map<string, string> labels = 5;

  string cleanupPayload = 6;      // cleanup payload is injected into the agent for a shutdown procedure  
}

```

Any reason not to use this?

My idea would be to apply all runner's labels to the task + some additional ones like runner's name and ID. Example:
```json
// runner 
{
  "id" :"123",
  "name": "mac",
  "labels": { "cpu.cores": "4" }
}
```

then, once task is sent to the runner, we apply runner's labels with the prefix and task becomes:

```json
{
  "id": "555",
  "labels": { "runner.id": "123", "runner.name": "mac", "runner.cpu.cores": "4" }
}
```

**Comment by alaric-dotmesh** [comment]
@rusenask I think it'd be cleaner to pass the runner's labels in to the agent docker image directly rather than via the task labels. How about we make `docker.go` feed them in as environment variables: `-e RUNNER.id=123 -e RUNNER.name=mac -e RUNNER.cpu.cores=4`?

**Comment by alaric-dotmesh** [comment]
However, if you can feed them into the agent docker image, through whatever means, I'll be able to pick them up from there and feed them down into the committer to put them in the run metadata! :-)

**Comment by rusenask** [comment]
what starts this container? agent?

**Comment by alaric-dotmesh** [comment]
The runner starts the agent container; the agent starts the app container, and also the committer container - and the committer container is the one that records all the metadata, so is where all this stuff needs to end up. However, the runner knows nothing of the committer, so needs to pass what i knows to the agent (the one it DOES start) which is then responsible for passing it on.

**Comment by rusenask** [comment]
Here you go https://github.com/dotmesh-io/ds-runner/commit/6dcbec5c184c03e38ea682bff0e4c0fe5156dc98 :P

**Comment by alaric-dotmesh** [comment]
HUGS AND KISSES :-D

**Comment by alaric-dotmesh** [comment]
Ok, for `ds run`, we now have everything apart from the CPU/RAM used by the Docker image, the GPU stats (I want to find out more about what's useful to include and how to get it), and the "runner physical RAM" info is based on something from `/proc` that excludes kernel RAM usage and we don't know if it's ECC - we can get better data from `dmidecode`, but that'll involve giving the committer container  privs to read `/dev/mem`.

So I'm calling it a wrap for now, as that other stuff is all optional data.
